# Generated by Django 5.0 on 2024-05-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pdv_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordinamento')),
            ],
            options={
                'verbose_name': 'Tipo di piatto',
                'verbose_name_plural': 'Tipi di piatto',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('procedure', models.TextField(verbose_name='Procedimento')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del menu')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'menu_management'), ('model', 'pdvmenu')), models.Q(('app_label', 'menu_management'), ('model', 'eventmenu')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo di menu')),
                ('dish_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu_management.dishtype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Piatto',
                'verbose_name_plural': 'Piatti',
            },
        ),
        migrations.CreateModel(
            name='EventMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('event_date', models.DateField(verbose_name='Data evento')),
                ('number_of_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_menus', to='pdv_management.pdv', verbose_name='PDV')),
            ],
            options={
                'verbose_name': 'Menu Evento',
                'verbose_name_plural': 'Menu Eventi',
            },
        ),
        migrations.CreateModel(
            name='PDVMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_menus', to='pdv_management.pdv', verbose_name='PDV')),
            ],
            options={
                'verbose_name': 'Menu PDV',
                'verbose_name_plural': 'Menu PDV',
            },
        ),
        migrations.CreateModel(
            name='QuantityIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.CharField(max_length=50, verbose_name='Quantità')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_management.dish', verbose_name='Piatto')),
            ],
            options={
                'verbose_name': 'Quantità Ingrediente',
                'verbose_name_plural': 'Quantità Ingredienti',
            },
        ),
    ]
