# Generated by Django 5.0 on 2024-06-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='quantityingredient',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='quantityingredient',
            name='object_id',
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmenu',
            name='dishes',
            field=models.ManyToManyField(related_name='%(class)s_dishes', to='menu_management.dish', verbose_name='Piatti'),
        ),
        migrations.AddField(
            model_name='eventmenu',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdvmenu',
            name='dishes',
            field=models.ManyToManyField(related_name='%(class)s_dishes', to='menu_management.dish', verbose_name='Piatti'),
        ),
    ]
