# Generated by Django 4.2.7 on 2023-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('dish_type', models.CharField(choices=[('entree', 'Antipasto'), ('first_dish', 'Primo piatto'), ('second_dish', 'Secondo piatto'), ('side_dish', 'Contorno'), ('dessert', 'Dessert'), ('other', 'Altro')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='entree',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='first_dish',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='other',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='second_dish',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='side_dish',
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='Entree',
        ),
        migrations.DeleteModel(
            name='First_dish',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='Second_dish',
        ),
        migrations.DeleteModel(
            name='Side_dish',
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, to='menu_management.dish'),
        ),
    ]
